django_board/board/urls.py
from django.conf.urls import url
from board.views import *

urlpatterns = [
    url(r'^$', BoardLV.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', BoardDV.as_view(), name='detail'),

    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    # Example: /tag/tagname/
    url(r'^tag/(?P<tag>[^/]+(?u))/$', BoardTOL.as_view(), name='tagged_object_list'),

    url (r'^search/$', SearchFormView.as_view(), name='search'),

    # Example: /add/
    url(r'^add/$',
        BoardCreateView.as_view(), name="add",
    ),

    # Example: /change/
    url(r'^change/$',
        BoardChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    url(r'^(?P<pk>[0-9]+)/update/$',
        BoardUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$',
        BoardDeleteView.as_view(), name="delete",
    ),
]

django_board/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^board/', include('board.urls', namespace='board')),
]

django_board/board/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.core.urlresolvers import reverse
from tagging.fields import TagField
from django.contrib.auth.models import User


# Create your models here.

@python_2_unicode_compatible
class Board(models.Model):
    title = models.CharField('TITLE', max_length=50)
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    owner = models.ForeignKey(User, null=True)
    tag = TagField()

    class Meta:
        ordering  = ('-create_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.pk,))

    def save(self, *args, **kwargs):
        super(Board, self).save(*args, **kwargs)

    #def get_previous_post(self):
    #    return self.get_previous_by_create_date()

    #def get_next_post(self):
    #    return self.get_next_by_create_date()

django_board/board/forms.py
from django import forms

class BoardSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

django_board/board/views.py
from django.views.generic import ListView, DetailView, TemplateView

from board.models import Board
from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList

from django.views.generic.edit import FormView
from board.forms import BoardSearchForm
from django.db.models import Q
from django.shortcuts import render

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from mysite.views import LoginRequiredMixin


# Create your views here.

#--- ListView
class BoardLV(ListView) :
    model = Board
    #context_object_name = 'posts'
    paginate_by = 7

#--- DetailView
class BoardDV(DetailView) :
    model = Board

#-- Tag
class TagTV(TemplateView) :
    template_name = 'tagging/tagging_cloud.html'

class BoardTOL(TaggedObjectList) :
    model = Board
    template_name = 'tagging/tagging_board_list.html'

#--- FormView
class SearchFormView(FormView):
    form_class = BoardSearchForm
    template_name = 'board/board_search.html'

    def form_valid(self, form) :
        schWord = '%s' % self.request.POST['search_word']
        board_list = Board.objects.filter(Q(title__icontains=schWord) | Q(content__icontains=schWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = schWord
        context['object_list'] = board_list

        return render(self.request, self.template_name, context)

class BoardCreateView(LoginRequiredMixin, CreateView):
    model = Board
    fields = ['title', 'content', 'tag']
    success_url = reverse_lazy('board:list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(BoardCreateView, self).form_valid(form)

class BoardChangeLV(LoginRequiredMixin, ListView):
    template_name = 'board/Board_change_list.html'

    def get_queryset(self):
        return Board.objects.filter(owner=self.request.user)

class BoardUpdateView(LoginRequiredMixin, UpdateView) :
    model = Board
    fields = ['title', 'content', 'tag']
    success_url = reverse_lazy('board:list')

class BoardDeleteView(LoginRequiredMixin, DeleteView) :
    model = Board
    success_url = reverse_lazy('board:list')

django_board/mysite/views.py
from django.views.generic.base import TemplateView

from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy

from django.contrib.auth.decorators import login_required
# Create your views here.

#--- TemplateView
class HomeView(TemplateView):
    template_name = 'home.html'

#--- User Creation
class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

#--- @login_required
class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)

django_board/board/templates/board/board_change_list.html
{% extends "base.html" %}

{% block title %}board_change_list.html{% endblock %}

{% block content %}
<div id="content">

    <h1>Board Change - {{user}}</h1>

    <table class="change-list">
        <tr>
            <th>Title</th>
            <th>Content</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>

        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.content }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'board:update' item.id %}">Update</a></td>
            <td><a href="{% url 'board:delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

django_board/board/templates/board/board_confirm_delete.html
{% extends "base.html" %}

{% block title %}post_confirm_delete.html{% endblock %}

{% block content %}
<div id="content">

    <h1>Board Delete</h1>

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>

</div>
{% endblock %}

django_board/board/templates/board/board_detail.html
{% extends "base.html" %}

{% block title %}board_detail.html{% endblock %}

{% block content %}

<div id="content">
    <h1>게시글</h1>


    <table>
      <tr>
      <td><h1>제목 : {{ object.title }} </h1></td>
      </tr>

      <tr>
      <td>작성자 : {{ board.owner }}</td>
      </tr>

      <tr>
      <td>게시일 : {{ board.create_date }}</td>
      </tr>

      <tr>
      <td>내용 : {{ object.content }}<td>
      </tr>

      <tr>
        {% load tagging_tags %}
        {% tags_for_object object as tags %}
      <td>태그 :
        {% for tag in tags %}
        <a href="{% url 'board:tagged_object_list' tag.name %}">{{tag.name}}</a>
      {% endfor %}
    </td>
    <a href="/board/{{ object.id }}/update/">수정</a> / <a href="/board/{{ object.id }}/delete/">삭제</a>
      </tr>
      </table>
</div>




{% endblock content %}

django_board/board/templates/board/board_form.html
{% extends "base.html" %}

{% block title %}board_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">

    <h1>Board Create/Update - {{user}}</h1>

    <form action="." method="post">{% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}

    <p>This is a creation or update form for your board.</p>

    <fieldset class="aligned">

        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>

        <div class="form-row">
            {{ form.content.label_tag }} {{ form.content }}
        </div>

        <div class="form-row">
            {{ form.tag.label_tag }} {{ form.tag }}
        </div>

    </fieldset>

    <div class="submit-row">
        <input type="submit" value="Submit"/>
    </div>

    <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>

</div>
{% endblock %}

django_board/board/templates/board/board_list.html
{% extends "base.html" %}

{% block title %}board_list.html{% endblock %}

{% block content %}

<div id="content">
    <h1>게시글</h1>
    <a href="{% url 'board:add' %}">게시글 작성</a>


    <table>
        <tr>
        <td>작성자</td>
        <td>제목</td>
        <td>게시일</td>
        </tr>

        {% for board in object_list %}
        <tr>
        <td>{{ board.owner }}</td>
        <td><a href="/board/{{board.id}}/">{{ board }}</a></td>
        <td>{{ board.create_date }}</td>
        </tr>
        {% endfor %}

    </table>

    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>

</div>
{% endblock content %}

django_board/board/templates/board/board_search.html
{% extends "base.html" %}

{% block title %}board_search.html{% endblock %}

{% block content %}
<div id="content">

<h1>게시판 검색</h1>

<form action="." method="post"> {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit" />
</form>

<br/><br/>

{% if object_list %}
{% for board in object_list %}
    <h2>{{ board.title }}</a></h2>
    {{ board.create_date|date:"N d, Y" }}
    <p>{{ board.content }}</p>
{% endfor %}

{% elif search_term %}
<b><i>Search Word({{ search_term }}) Not Found !</i></b>
{% endif %}

</div>
{% endblock %}

django_board/board/templates/tagging/tagging_cloud.html
{% extends "base.html" %}

{% block title %}tagging_cloud.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "tagging/tag.css" %}{% endblock %}

{% block content %}
<div id="content">

<h1>board Tag Cloud</h1>

<div class="tag-cloud">
    {% load tagging_tags %}
    {% tag_cloud_for_model board.board as tags with steps=6 min_count=1 distribution=log %}
    {% for tag in tags %}
    <span class="tag-{{tag.font_size}}">
        <a href="{% url 'board:tagged_object_list' tag.name %}">{{tag.name}}</a>
    </span>
    {% endfor %}
</div>

</div>
{% endblock %}

django_board/board/templates/tagging/tagging_post_list.html
{% extends "base.html" %}

{% block title %}tagging_board_list.html{% endblock %}

{% block content %}
<div id="content">

<h1>boards for tag - {{ tag.name }}</h1>

{% for board in object_list %}
    <h2><a href='{{ board.get_absolute_url }}'>{{ board.title }}</a></h2>
    {{ board.modify_date|date:"N d, Y" }}
    <p>{{ board.description }}</p>
{% endfor %}

</div>
{% endblock %}

django_board/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %}Django Web Programming{% endblock %}</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

<div id="header">
    <h2 class="maintitle">Ney's Board</h2>
    {% if user.is_active %}
    <h4 class="welcome">Welcome,
                <strong>{% firstof user.get_short_name user.get_username %}</strong> /
                <a href="{% url 'password_change' %}">Change Password</a> /
                <a href="{% url 'logout' %}">Logout</a>
    </h4>
    {% else %}
    <h4 class="welcome">Welcome, Anonymous /
                <a href="{% url 'login' %}">Login</a> /
                <a href="{% url 'register' %}">Register</a>
    </h4>
    {% endif %}
</div>

<div id="menu">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'board:list' %}">Board</a></li>
    <li><a href="{% url 'board:tag_cloud' %}">TagCloude</a></li>
    <li><a href="{% url 'board:search' %}">Search</a></li>
</div>

{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>
</html>

django_board/templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}

<div id="content_home">

    <div id="homeimg">
        <a href="/"><img src="{% static 'img/mr_ney.jpg' %}" style="height:256px;"/></a>
        <h4 style="margin: 0;">Ney's Board</h4>
    </div>

    <hr style="margin: 5px 0;">

    <h2>Select Application</h2>

    <table id="applist">
        <tr>
        <td><b><i><a href="{% url 'board:list' %}">Board</a></i><b></td>
        <td>게시판입니다.</td>
        </tr>


        <tr>
        <td><b><i><a href="{% url 'board:tag_cloud' %}">TagCloude</a></i><b></td>
        <td>태그의 빈도를 멋지게 정리하였습니다.</td>
        </tr>

        <tr>
        <td><b><i><a href="{% url 'board:search' %}">Search</a></i><b></td>
        <td>게시글에서 검색을 할 수 있습니다.</td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block footer %}

{% endblock footer %}